searchSpaceFile: space.json
trialCommand: python model.py 
trialGpuNumber: 1
trialConcurrency: 3
maxExperimentDuration: 12h
tuner:
  name: TPE
  classArgs:
    optimize_mode: maximize


trainingService:
  platform: local
  useActiveGpu: true
  maxTrialNumberPerGpu: 3